### ISSUE TITLE
Bad User experience

### ISSUE THREAD

**Issue by bastien03** [devbliss/doctest#41]
when showing a response with a big payload, the user experience is bad because it has to be scrolled down all the time. what could be done to improve this?

![screen shot 2014-04-08 at 10 33 27](https://cloud.githubusercontent.com/assets/496860/2641355/a86e7b6c-bef8-11e3-9eef-be8f94c6c26a.png)

**Comment by roughy** [comment]
moved this issue https://github.com/java-doctest/doctest/issues/2
