### ISSUE TITLE
AsciiDoc and PDF support

### ISSUE THREAD

**Issue by RobWin** [devbliss/doctest#50]
Hello,

could you please support AsciiDoc and PDF generation?

Shameless plug: You could use my https://github.com/RobWin/markup-document-builder,
if you don't want to create an own solution. From AsciiDoc you can easily generate HTML, PDF, EPUB.
I'm developing a similar solution like DocTest to document REST APIs using Swagger, swagger-springmvc and spring-restdocs.

https://github.com/RobWin/swagger2markup

Kind regards,

Robert Winkler

**Comment by bastien03** [comment]
Hi Robert,

I agree that supporting several output format would be a nice feature for doctest.
I label this issue as enhancement.

I'm not sure when we will be able to implement this but we would be very happy if you can provide a pull request.

Best,
bastien
